// <auto-generated />
using GestioneDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestioneDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122143518_Setted passwords structure")]
    partial class Settedpasswordsstructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestioneDb.Models.Password", b =>
                {
                    b.Property<string>("App")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CryptedPassword")
                        .HasColumnType("varbinary(max)");

                    b.ToTable("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
