name: Build Avalonia Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore GestorePassword/GestorePassword.Desktop/GestorePassword.Desktop.csproj

    - name: Build
      run: dotnet build GestorePassword/GestorePassword.Desktop/GestorePassword.Desktop.csproj -c Release --no-restore

    - name: Publish
      run: dotnet publish GestorePassword/GestorePassword.Desktop/GestorePassword.Desktop.csproj -c Release -o output
